name: reellife
favicon: null
layout_spectrum: 0.6890156192239374
typography_spectrum: 0.865147503791377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7146390869747847
  lightness: 0.019203445175662637
  saturation: 0.2925060570705682
  rhythmicContrast: 0.703257515328005
purpose: []
