name: reellife
favicon: null
layout_spectrum: 0.13749
typography_spectrum: 0.50954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.703257515328005
purpose: []
